name: 'pandoc'

on:
  push:
    branches:
    - main
    - master
  pull_request:
    branches:
    - main
    - master

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-FUN-400-PAR-4-1-mypandoc-martin.fillon.git"

jobs:
  check_stack_build:
    runs-on: ubuntu-latest
    name: Building stack
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check stack install
        timeout-minutes: 5
        run: |
          sudo make re

  push_to_mirror:
    needs: [check_stack_build]
    if: ${{ github.event_name == 'push' }}
    name: "pushes all files to mirror specified"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.KEY }}
