name: 'pandoc'

on:
  push:
    branches:
    - main
    - master
  pull_request:
    branches:
    - main
    - master

jobs:
  make_tests_run:
    runs-on: ubuntu-latest
    name: run tests
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check tests
        timeout-minutes: 5
        run: |
          sudo make tests_run
